# frozen_string_literal: true

source 'https://rubygems.org'

group :develop do
  gem 'rubocop', '>= 1.65.0'
  gem 'rubocop-rspec', '>= 3.0.0'
end

group :test do
  gem 'bosh-template'
  gem 'rspec'
end
